name: CI
on: push
jobs:
  ci:
    name: CI
    uses: mauriciabad/my-actions/.github/workflows/ci-vite.yml@main
    with:
      lighthouse: true
    secrets:
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
