name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    name: CI - test
    steps:
      - name: âš™ï¸ Setup
        uses: mauriciabad/my-actions/setup-npm@main
      - run: npm run build
      - run: npm run test:e2e
